// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service. All exported methods are callable from
 * the frontend via Wails3 generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Greet returns a greeting for the given name.
 * Callable from the frontend via generated bindings.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(3470321134, name);
}

/**
 * OpenNewWindow creates a new WebviewWindow with the given title.
 * Callable from the frontend via generated bindings.
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function OpenNewWindow(title) {
    return $Call.ByID(4160192041, title);
}

/**
 * SetApp injects the Wails application reference. Must be called before Run().
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(2689798946, app);
}
